# Generated by Django 5.0.6 on 2024-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.CharField(default='https://www.svgrepo.com/show/66980/fast-food-placeholder.svg', max_length=500),
        ),
    ]
